base:
  m: 100
  n: 200
  tol: 1e-4
  max_iter: 1000
  r0: 10
  save_dir: "../output/fig2/"

outer_iter    : 10   
outer_tol     : 1e-3  
admm_iter     : 30    
admm_tol      : 1e-4   
admm_rho      : 5e-2   
apgl_iter     : 30    
apgl_tol      : 1e-4   
apgl_lambda   : 5e-2
admmap_iter   : 30  
admmap_tol    : 1e-4 
admmap_rho    : 2    
admmap_kappa  : 1e-3
admmap_beta   : 1 
admmap_betamax: 1e10