base:
  img_path: "../assets/building.jpg"
  # mask_path: "../assets/string.jpg"
  obs_p: 0.5  # 1 - obs_p = mask percent
  save_dir: "../output/fig4v2/"
  fig_name: "fig4"
  tol: 1e-4
  max_iter: 100
  r0: 10
  SVT_power: 0.75
clip_type  : 0 # 0 -> no 1 -> uint8 2 -> 0~1
outer_iter : 100
outer_tol  : 1e-3  
inner_iter : 200
tol        : 1e-4
rho0       : 1.1
lambda     : 1e-3
kappa      : 1e-3
beta       : 1e-3
beta_max   : 1e10
min_R      : 5
max_R      : 5