base:
  tol: 1e-4
  max_iter: 100
  img_path: "../assets/building.jpg"
  # mask_path: "../assets/string.jpg"
  save_dir: "../output/fig5/"
  fig_name: "fig5"
  SVT_power : 0.85

clip_type  : 0 # 0 -> no 1 -> uint8 2 -> 0~1
outer_iter : 100
outer_tol  : 1e-3  
inner_iter : 200
tol        : 1e-4
rho0       : 1.1
lambda     : 1e-2
kappa      : 1e-3
beta       : 1e-3
beta_max   : 1e10
min_R      : 5
max_R      : 5